# Generated by Django 5.2.4 on 2025-07-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='technologies',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
